### ISSUE TITLE
[meta] How to Submit an Issue

### ISSUE THREAD

**Issue by pbwebdev** [joomla-projects/accessibility#7]
@roland-d 

Can I get some help in sorting out a standard way of submitting issues for this?

Default content that we're using to test against, I'm using 'LEARN' Sample data

Formatting of issue submitted
Title - E.g Componment/module/template - Issue description?

Something on the lines of that? No idea really. I'm making it up as I go at the moment.

**Comment by roland-d** [comment]
@pbwebdev The standard way in my opinion should be as follows.

## Descriptive Title

### Description of the issue

### What happens

### What do you expect

### Steps to reproduce

### How to fix (in case you know what needs to be changed)

**Comment by brianteeman** [comment]
You can create a template on github for reporting issues https://help.github.com/articles/creating-an-issue-template-for-your-repository/

**Comment by roland-d** [comment]
Thank you @brianteeman Template has been made. It is in the main folder so we can edit as needed.

@pbwebdev Where or what is the 'LEARN' sample data?

**Comment by brianteeman** [comment]
"LEARN" is one of the sample data sets available when you install

On 29 May 2016 at 09:07, RolandD <notifications@github.com> wrote:

> Thank you @brianteeman <https://github.com/brianteeman> Template has been
> made. It is in the main folder so we can edit as needed.
>
> @pbwebdev <https://github.com/pbwebdev> Where or what is the 'LEARN'
> sample data?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla-projects/accessibility/issues/7#issuecomment-222348212>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8c0G0grBXarRHvTQJ9latUSbXwSgks5qGUkrgaJpZM4InINq>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by armenos** [comment]
I would like to respond to the question about standard way of submitting issues. My comment is only about the title for the issues, the rest we try to describe as well as possible like @roland-d has proposed.

During my meeting with Roland I proposed to submit the issues from success criterias of WCAG 2.0 AA. Thus we can easily look back for issues and remain structured. And also because we want to meet the minimum standard for governments (WCAG 2.0 AA). Well I'm going to do my best to ensure that the reader understands what is going on the subject. I'll create a new issue these days and see how this is done.

Example of title: [SC 2.4.1] Bypass Blocks: navigation mechanisms to skip links (frontend-template)

**Comment by roland-d** [comment]
@armenos I will update the template to include the SC as XX. I believe this can be closed now, feel free to re-open if needed.
